- name: Deploy on OpenStack
  hosts: 10.1.0.12
  gather_facts: false
  tasks:
    - name: Deploy an instance
      os_server:
        state: present
        name: webserver
        image: cirros
        key_name: alan_key
        wait: yes
        flavor: m1.tiny
        auto_ip: no
        network: private
        meta:
          hostname: webserver.localdomain
